### ISSUE TITLE
Proxy takes first opened port (may not be the web one)

### ISSUE THREAD

**Issue by ysbaddaden** [manastech/dockerdev#3]
As found out by @matiasgarciaisaia in https://github.com/manastech/dockerdev/pull/1#issuecomment-1464116452:

> I've checked & confirmed that the issue is that dockerdev picks the website's 1234 port (used for hot-reloading) instead of 4567 (the web server itself). So dockerdev works (checked the ARM image too), but maybe the issue would be how to support multi-port containers - an independent issue itself.

It appears that the proxy is using the first opened (or exposed?) port from the container to redirect the web traffic to.

**Comment by ysbaddaden** [comment]
It looks like the port is decided on this line:
https://github.com/manastech/dockerdev/blob/master/nginx.tmpl#L54

It looks for the `VIRTUAL_PORT` then the first port of the first address for the container, and eventually falls back to port 80.

Setting `VIRTUAL_PORT` might fix this? I think I saw that envvar in a few compose configs, and wondered what the heck it was.

**Comment by ysbaddaden** [comment]
Confirmed: adding `VIRTUAL_PORT` to compose, the nginx proxy picks port 4567 to redirect the traffic to. Without, it picks port 1234.

```yaml
services:
  web:
    environment:
      VIRTUAL_PORT: "4567"
```

Poke @matiasgarciaisaia

**Comment by ysbaddaden** [comment]
I documented the variable in 77c2499bb56cd7f95c8133aaf57b405aa8c4e965

**Comment by matiasgarciaisaia** [comment]
Great, @ysbaddaden!
